import { useState } from "react";
import type { ClearLamp, HighestDpRank, SetupRegistrationMethod } from "../../domain/types";
import type { SetupDraftState } from "../../setup/types";

const lamps: ClearLamp[] = ["NO_PLAY", "FAILED", "ASSIST_CLEAR", "EASY_CLEAR", "CLEAR", "HARD_CLEAR", "EX_HARD_CLEAR", "FULL_COMBO"];
const ranks: readonly [HighestDpRank, string][] = [["UNOBTAINED", "未取得"], ["EIGHTH_OR_BELOW", "八段以下"], ["NINTH", "九段"], ["TENTH", "十段"], ["CHUDEN", "中伝"], ["KAIDEN", "皆伝"]];

export function SetupScreen({ state, charts, onRank, onMethod, onBulk, onCorrect, onComplete, onDiscard, onOfficialCsv }: { state: SetupDraftState; charts: readonly { chartId: string; label: string }[]; onRank: (rank: HighestDpRank) => Promise<void>; onMethod: (method: SetupRegistrationMethod) => Promise<void>; onBulk: (level: 10 | 11 | 12, lamp: ClearLamp) => Promise<void>; onCorrect: (chartId: string, lamp: ClearLamp) => Promise<void>; onComplete: () => Promise<void>; onDiscard: () => Promise<void>; onOfficialCsv: (text: string) => Promise<void>; }) {
  const [csv, setCsv] = useState(""); const [message, setMessage] = useState(""); const [lamp, setLamp] = useState<ClearLamp>("CLEAR"); const [query, setQuery] = useState(""); const [chartId, setChartId] = useState("");
  const matches = charts.filter(chart => !query.trim() || chart.label.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).slice(0, 50);
  const ready = Boolean(state.draft.highestDpRank && state.draft.selectedRegistrationMethod);
  const importOfficial = (text: string) => void onOfficialCsv(text).then(() => setMessage("公式CSVを解析して下書きへ反映しました。")).catch(error => setMessage(String(error)));
  const readOfficial = (file: File | null) => { if (file) void file.text().then(importOfficial).catch(error => setMessage(String(error))); };
  return <section><h1>初回セットアップ</h1><label>DP最高段位<select value={state.draft.highestDpRank ?? ""} onChange={event => void onRank(event.target.value as HighestDpRank)}><option value="" disabled>選択してください</option>{ranks.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>{state.draft.highestDpRank && <div className="buttons"><button onClick={() => void onMethod("official_csv")}>公式CSV</button><button onClick={() => void onMethod("manual")}>手動登録</button><button onClick={() => void onMethod("later")}>後で登録</button></div>}{state.draft.selectedRegistrationMethod === "official_csv" && <><label>公式CSVファイル<input type="file" accept=".csv,text/csv" onChange={event => readOfficial(event.target.files?.[0] ?? null)} /></label><details><summary>公式CSVを貼り付ける</summary><textarea aria-label="公式CSV" value={csv} onChange={event => setCsv(event.target.value)} /><button disabled={!csv} onClick={() => importOfficial(csv)}>CSVを解析して下書き保存</button></details><output>{message}</output></>}{state.draft.selectedRegistrationMethod === "manual" && <><label>設定ランプ<select value={lamp} onChange={event => setLamp(event.target.value as ClearLamp)}>{lamps.map(value => <option key={value}>{value}</option>)}</select></label><div className="buttons">{([10, 11, 12] as const).map(level => <button key={level} onClick={() => void onBulk(level, lamp)}>☆{level}へ以上を一括設定</button>)}</div><label>例外修正検索<input type="search" value={query} onChange={event => { setQuery(event.target.value); setChartId(""); }} /></label><label>例外修正<select value={chartId} onChange={event => setChartId(event.target.value)}><option value="">譜面を選択</option>{matches.map(chart => <option key={chart.chartId} value={chart.chartId}>{chart.label}</option>)}</select></label><button disabled={!chartId} onClick={() => void onCorrect(chartId, lamp)}>選択譜面を修正</button></>}<p>下書き登録数: {state.payload.stagedRecords.length}</p><button disabled={!ready} onClick={() => void onComplete()}>この内容で開始</button><button onClick={() => void onDiscard()}>最初からやり直す</button></section>;
}
