import { useMemo, useState } from "react";
import { RADAR_DISPLAY_ORDER } from "../../domain/constants";
import { isCurrentlyPlayableChart } from "../../domain/chart";
import type { ChartMaster, PlayerRadarDetails, RadarAttribute } from "../../domain/types";
import type { MasterSet } from "../../master/types";
const title=(m:MasterSet,c:ChartMaster)=>m.chartMaster.songs.find(s=>s.songId===c.songId)?.title??c.chartId;
const label=(a:RadarAttribute)=>a==="SOF_LAN"?"SOF-LAN":a;
const clone=(d:PlayerRadarDetails)=>Object.fromEntries(RADAR_DISPLAY_ORDER.map(a=>[a,d[a].map(x=>({...x}))])) as PlayerRadarDetails;
export function normalizeRadarDetails(master:MasterSet, details:PlayerRadarDetails):PlayerRadarDetails { const charts=new Map(master.chartMaster.charts.map(c=>[c.chartId,c])); return Object.fromEntries(RADAR_DISPLAY_ORDER.map(a=>{const best=new Map<string,{chartId:string;value:number;index:number}>();details[a].forEach((x,index)=>{const key=charts.get(x.chartId)?.songId??`chart:${x.chartId}`, old=best.get(key);if(!old||x.value>old.value)best.set(key,{...x,index});});return[a,[...best.values()].sort((l,r)=>r.value-l.value||l.index-r.index||l.chartId.localeCompare(r.chartId)).slice(0,10).map(({chartId,value})=>({chartId,value}))]})) as PlayerRadarDetails; }
export function PlayerRadarDetailsEditor({master,details,onSave}:{master:MasterSet;details:PlayerRadarDetails;onSave:(details:PlayerRadarDetails)=>Promise<void>}) {const[attribute,setAttribute]=useState<RadarAttribute>("NOTES"),[query,setQuery]=useState(""),[chartId,setChartId]=useState(""),[value,setValue]=useState(""),[message,setMessage]=useState("");const normalized=normalizeRadarDetails(master,details),entries=normalized[attribute],charts=new Map(master.chartMaster.charts.map(c=>[c.chartId,c]));const choices=useMemo(()=>master.chartMaster.charts.filter(isCurrentlyPlayableChart).filter(c=>!query||`${title(master,c)} ${c.chartType}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).slice(0,50),[master,query]);const persist=async(n:PlayerRadarDetails,s:string)=>{await onSave(normalizeRadarDetails(master,n));setMessage(s)};const save=async()=>{const numeric=Number(value),chart=charts.get(chartId);if(!chart||!Number.isFinite(numeric)||numeric<0){setMessage("譜面と0以上の数値を入力してください。");return}const next=clone(normalized),same=next[attribute].find(x=>charts.get(x.chartId)?.songId===chart.songId);if(same&&numeric<=same.value){setMessage("同一曲が登録済みのため、高い値の譜面を使用しました。");return}if(same)next[attribute]=next[attribute].filter(x=>x.chartId!==same.chartId);if(!same&&next[attribute].length>=10){setMessage("各属性は10曲までです。");return}next[attribute].push({chartId,value:numeric});await persist(next,same?"同一曲が登録済みのため、高い値の譜面へ置換しました。":"Radar詳細を保存しました。");setValue("")};const remove=async(id:string)=>{const next=clone(normalized);next[attribute]=next[attribute].filter(x=>x.chartId!==id);await persist(next,"Radar詳細を削除しました。")};return <section className="radar-details"><h3>NOTES RADAR 詳細</h3><label>属性<select value={attribute} onChange={e=>{setAttribute(e.target.value as RadarAttribute);setChartId("");setValue("")}}>{RADAR_DISPLAY_ORDER.map(a=><option key={a} value={a}>{label(a)}</option>)}</select></label><label>曲名検索<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>譜面<select value={chartId} onChange={e=>{const id=e.target.value;setChartId(id);setValue(entries.find(x=>x.chartId===id)?.value.toString()??"")}}><option value="">選択してください</option>{choices.map(c=><option key={c.chartId} value={c.chartId}>{title(master,c)} {c.chartType}</option>)}</select></label><label>個人Radar詳細値<input type="number" min="0" step="any" value={value} onChange={e=>setValue(e.target.value)}/></label><button onClick={()=>void save().catch(e=>setMessage(String(e)))}>登録・更新</button><p className="hint">{entries.length}/10曲</p>{entries.map((x,i)=>{const c=charts.get(x.chartId);return <div className="detail-row" key={x.chartId}><span>{i+1}. {c?`${title(master,c)} ${c.chartType}`:x.chartId} / {x.value}</span><button className="secondary" onClick={()=>void remove(x.chartId).catch(e=>setMessage(String(e)))}>削除</button></div>})}<output>{message}</output></section>}
