import { CLEAR_LAMP_RANK } from "../domain/constants";
import { effectiveDifficulty, isManagedChart } from "../domain/chart";
import { validateScoreForChart } from "../domain/score";
import type { ChartMaster, ClearLamp, HistoryEntry, PlayerChartRecord, SongMaster } from "../domain/types";
import { escapeCsv, parseCsv } from "./csv";

export const CLEAR_TRACKER_CSV_HEADERS = ["formatVersion", "chartId", "title", "chartType", "debutVersion", "officialLevel", "unofficialDifficulty", "clearLamp", "score", "bp"] as const;
const lamps: Readonly<Record<string, ClearLamp>> = { "NO PLAY": "NO_PLAY", FAILED: "FAILED", "ASSIST CLEAR": "ASSIST_CLEAR", "EASY CLEAR": "EASY_CLEAR", CLEAR: "CLEAR", "HARD CLEAR": "HARD_CLEAR", "EX HARD CLEAR": "EX_HARD_CLEAR", "FULL COMBO": "FULL_COMBO" };
const displayLamp = (lamp: ClearLamp): string => Object.entries(lamps).find(([, value]) => value === lamp)![0];
export interface ClearTrackerImportChange { chartId: string; before: PlayerChartRecord | undefined; after: PlayerChartRecord; lampChanged: boolean; scoreChanged: boolean; bpChanged: boolean; }
export interface ClearTrackerImportPreview { changes: ClearTrackerImportChange[]; errors: string[]; rowCount: number; }
const sameHeaders = (headers: readonly string[]) => headers.length === CLEAR_TRACKER_CSV_HEADERS.length && headers.every((header, index) => header === CLEAR_TRACKER_CSV_HEADERS[index]);
const numberOrBlank = (value: string, label: string): number | undefined => { if (value === "") return undefined; if (!/^\d+$/.test(value)) throw new Error(`${label} must be a non-negative integer.`); return Number(value); };

export function exportClearTrackerCsv(charts: readonly ChartMaster[], songs: readonly SongMaster[], unofficialByChartId: ReadonlyMap<string, number>, records: readonly PlayerChartRecord[]): string {
  const songById = new Map(songs.map((song) => [song.songId, song])); const recordByChartId = new Map(records.map((record) => [record.chartId, record])); const lines = [CLEAR_TRACKER_CSV_HEADERS.join(",")];
  for (const chart of charts.filter(isManagedChart)) { const song = songById.get(chart.songId); if (!song) throw new Error(`chart '${chart.chartId}' has no SongMaster.`); const record = recordByChartId.get(chart.chartId); const difficulty = effectiveDifficulty(chart, unofficialByChartId.has(chart.chartId) ? { difficulty: unofficialByChartId.get(chart.chartId)! } : null); lines.push([1, chart.chartId, song.title, chart.chartType, song.debutVersion ?? "", chart.officialLevel, difficulty, displayLamp(record?.clearLamp ?? "NO_PLAY"), record?.score ?? "", record?.bp ?? ""].map(escapeCsv).join(",")); }
  return `\uFEFF${lines.join("\r\n")}\r\n`;
}
export function previewClearTrackerCsv(text: string, playerId: string, charts: readonly ChartMaster[], currentRecords: readonly PlayerChartRecord[], now: string): ClearTrackerImportPreview {
  const rows = parseCsv(text); if (rows.length === 0 || !sameHeaders(rows[0])) throw new Error("CLEAR TRACKER CSV header is invalid."); const master = new Map(charts.map((chart) => [chart.chartId, chart])); const records = new Map(currentRecords.map((record) => [record.chartId, record])); const seen = new Set<string>(); const errors: string[] = []; const changes: ClearTrackerImportChange[] = [];
  rows.slice(1).forEach((row, offset) => { const line = offset + 2; try { if (row.length !== CLEAR_TRACKER_CSV_HEADERS.length) throw new Error("column count is invalid."); const [version, chartId, , , , , , lampText, scoreText, bpText] = row; if (version !== "1") throw new Error("formatVersion must be 1."); if (!chartId) throw new Error("chartId is required."); if (seen.has(chartId)) throw new Error("chartId is duplicated."); seen.add(chartId); const chart = master.get(chartId); if (!chart) throw new Error("chartId is not in CHART_MASTER."); if (!isManagedChart(chart)) throw new Error("chartId is outside the current management scope."); const lamp = lampText === "" ? undefined : lamps[lampText]; if (lampText !== "" && !lamp) throw new Error("clearLamp is invalid."); const score = numberOrBlank(scoreText, "score"); validateScoreForChart(score, chart); const bp = numberOrBlank(bpText, "bp"); const before = records.get(chartId); const base: PlayerChartRecord = before ?? { playerId, chartId, clearLamp: "NO_PLAY", score: null, bp: null, clearSource: null, scoreSource: null, bpSource: null, updatedAt: now }; const lampChanged = lamp !== undefined && lamp !== base.clearLamp; const scoreChanged = score !== undefined && score !== base.score; const bpChanged = bp !== undefined && bp !== base.bp; if (lampChanged || scoreChanged || bpChanged) changes.push({ chartId, before, after: { ...base, clearLamp: lamp ?? base.clearLamp, score: score ?? base.score, bp: bp ?? base.bp, clearSource: lampChanged ? "tracker_template" : base.clearSource, scoreSource: scoreChanged ? "tracker_template" : base.scoreSource, bpSource: bpChanged ? "tracker_template" : base.bpSource, updatedAt: now }, lampChanged, scoreChanged, bpChanged }); } catch (error) { errors.push(`Row ${line}: ${error instanceof Error ? error.message : String(error)}`); } });
  return { changes, errors, rowCount: rows.length - 1 };
}
export function createImportHistory(changes: readonly ClearTrackerImportChange[], playerId: string, now: string, historyId: () => string): HistoryEntry[] { return changes.filter((change) => change.lampChanged && CLEAR_LAMP_RANK[change.after.clearLamp] > CLEAR_LAMP_RANK[change.before?.clearLamp ?? "NO_PLAY"]).map((change) => ({ historyId: historyId(), playerId, date: now, chartId: change.chartId, oldLamp: change.before?.clearLamp ?? "NO_PLAY", newLamp: change.after.clearLamp, source: "tracker_template" })); }
