import { useEffect, useMemo, useState } from "react";
import type { ClearLamp, HistoryEntry, Player, PlayerChartRecord, RadarAttribute } from "./domain/types";
import { isCurrentlyPlayableChart, isManagedChart } from "./domain/chart";
import { DataScreen } from "./features/data/DataScreen";
import { AnalysisScreen, chartTitle, HistoryScreen, HomeScreen, PlayerScreen, TrackerScreen, TrainingScreen } from "./features/dashboard/Screens";
import { QuickInput } from "./features/quick-input/QuickInput";
import { SetupScreen } from "./features/setup/SetupScreen";
import { createBackup, parseBackup, restoreBackup, validateBackupReferences } from "./import/backup";
import { exportClearTrackerCsv, previewClearTrackerCsv } from "./import/clear-tracker-csv";
import { commitClearTrackerPreview, commitRecordImport, updateQuickInput } from "./import/operations";
import { previewOfficialCsv } from "./import/official-csv";
import { loadMasterSet } from "./master/loader";
import type { MasterSet } from "./master/types";
import { applyInitialBulkLamp, beginSetup, completeSetup, correctInitialLamp, discardSetup, readSetupDraftState, replaceSetupStagedRecords, saveHighestDpRank, saveRegistrationMethod, updatePlayerEreterOverall, updatePlayerProfile, updatePlayerRadar, updatePlayerRadarDetails } from "./setup/service";
import type { SetupDraftState } from "./setup/types";
import { UserDataRepository } from "./storage/repository";
import { calculateTraining } from "./training/engine";
import { useNextTraining } from "./features/dashboard/useNextTraining";

type Screen = "HOME" | "TRAINING" | "TRACKER" | "QUICK" | "HISTORY" | "ANALYSIS" | "PLAYER" | "DATA";
const fetchJson = async (path: string) => { const response = await fetch(path); if (!response.ok) throw new Error(`Master load failed: ${path}`); return response.json(); };
const id = () => {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") return crypto.randomUUID();
  const random = typeof crypto !== "undefined" && typeof crypto.getRandomValues === "function"
    ? crypto.getRandomValues(new Uint32Array(4))
    : new Uint32Array([Math.random() * 0x1_0000_0000, Math.random() * 0x1_0000_0000, Math.random() * 0x1_0000_0000, Math.random() * 0x1_0000_0000]);
  return `${random[0].toString(16)}-${random[1].toString(16)}-${random[2].toString(16)}-${random[3].toString(16)}-${Date.now().toString(16)}`;
};
const download = (name: string, text: string, type: string) => { const url = URL.createObjectURL(new Blob([text], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };
const previewMessage = (records: number, errors: readonly string[]) => `登録候補 ${records}件、エラー ${errors.length}件。${errors.length ? `\n\n${errors.slice(0, 5).join("\n")}` : ""}\n\n正常な候補を反映しますか？`;
const dpRankLabel: Record<Player["highestDpRank"], string> = { UNOBTAINED: "未取得", EIGHTH_OR_BELOW: "八段以下", NINTH: "九段", TENTH: "十段", CHUDEN: "中伝", KAIDEN: "皆伝" };

export default function App() {
  const [repository, setRepository] = useState<UserDataRepository>(); const [master, setMaster] = useState<MasterSet>(); const [player, setPlayer] = useState<Player>(); const [playerRecords, setPlayerRecords] = useState<ReadonlyMap<string, PlayerChartRecord>>(new Map()); const [history, setHistory] = useState<HistoryEntry[]>([]); const [setup, setSetup] = useState<SetupDraftState>(); const [screen, setScreen] = useState<Screen>("HOME"); const [returnScreen, setReturnScreen] = useState<Screen>("HOME"); const [selectedChartId, setSelectedChartId] = useState<string>(); const [selectedTrainingAttribute, setSelectedTrainingAttribute] = useState<RadarAttribute>(); const [homeThreshold, setHomeThreshold] = useState<ClearLamp>("EASY_CLEAR"); const [playerThreshold, setPlayerThreshold] = useState<ClearLamp>("EASY_CLEAR"); const [error, setError] = useState("");
  const refresh = async (repo: UserDataRepository, active: Player) => { setPlayerRecords(new Map((await repo.listPlayerChartRecords(active.playerId)).map(record => [record.chartId, record]))); setHistory(await repo.listHistory(active.playerId)); };
  useEffect(() => { let opened: UserDataRepository | undefined; let cancelled = false; void Promise.all([UserDataRepository.open(), loadMasterSet(fetchJson)]).then(async ([repo, loadedMaster]) => { opened = repo; if (cancelled) return repo.close(); setRepository(repo); setMaster(loadedMaster); const players = await repo.listPlayers(); if (players[0]) { setPlayer(players[0]); await refresh(repo, players[0]); const [homeSetting, playerSetting] = await Promise.all([repo.getUiSetting(`homeThreshold:${players[0].playerId}`), repo.getUiSetting(`playerThreshold:${players[0].playerId}`)]); if (typeof homeSetting?.value === "string" && ["EASY_CLEAR", "CLEAR", "HARD_CLEAR", "EX_HARD_CLEAR", "FULL_COMBO"].includes(homeSetting.value)) setHomeThreshold(homeSetting.value as ClearLamp); if (typeof playerSetting?.value === "string" && ["EASY_CLEAR", "CLEAR", "HARD_CLEAR", "EX_HARD_CLEAR", "FULL_COMBO"].includes(playerSetting.value)) setPlayerThreshold(playerSetting.value as ClearLamp); } else { const drafts = await repo.listSetupDrafts(); setSetup(drafts[0] ? readSetupDraftState(drafts[0]) : await beginSetup(repo, id(), new Date().toISOString())); } }).catch(reason => setError(String(reason))); return () => { cancelled = true; opened?.close(); }; }, []);
  const songs = useMemo(() => new Map(master?.chartMaster.songs.map(song => [song.songId, song]) ?? []), [master]);
  const training = useMemo(() => player && master ? calculateTraining({ player, records: [...playerRecords.values()], master, selectedAttribute: selectedTrainingAttribute }) : undefined, [player, master, playerRecords, selectedTrainingAttribute]);
  const nextTraining = useNextTraining(player?.playerId, training?.recommendations.clearTargets ?? []);
  if (error) return <main><p>{error}</p></main>; if (!repository || !master) return <main>読み込み中…</main>;
  if (!player && setup) { const charts = master.chartMaster.charts.filter(chart => isManagedChart(chart) && isCurrentlyPlayableChart(chart)).map(chart => ({ chartId: chart.chartId, label: `${songs.get(chart.songId)?.title ?? chart.chartId} ${chart.chartType}` })); return <main><SetupScreen state={setup} charts={charts} onRank={async rank => setSetup(await saveHighestDpRank(repository, setup, rank, new Date().toISOString()))} onMethod={async method => setSetup(await saveRegistrationMethod(repository, setup, method, new Date().toISOString()))} onBulk={async (level, lamp) => setSetup(await applyInitialBulkLamp(repository, setup, master.chartMaster.charts, level, lamp, new Date().toISOString()))} onCorrect={async (chartId, lamp) => { const chart = master.chartMaster.charts.find(candidate => candidate.chartId === chartId); if (!chart) throw new Error("chart not found"); setSetup(await correctInitialLamp(repository, setup, chart, lamp, new Date().toISOString())); }} onOfficialCsv={async text => { const preview = previewOfficialCsv(text, setup.draft.playerId, master.chartMaster.songs, master.chartMaster.charts, setup.payload.stagedRecords, new Date().toISOString()); if (!confirm(previewMessage(preview.records.length, preview.errors))) return; setSetup(await replaceSetupStagedRecords(repository, setup, preview.records, new Date().toISOString())); }} onComplete={async () => { const next = await completeSetup(repository, setup, new Date().toISOString()); setPlayer(next); await refresh(repository, next); }} onDiscard={async () => { await discardSetup(repository, setup.draft.playerId); setSetup(await beginSetup(repository, id(), new Date().toISOString())); }} /></main>; }
  if (!player || !training) return <main>PLAYERがありません。</main>;
  const choices = master.chartMaster.charts.filter(chart => isManagedChart(chart) && isCurrentlyPlayableChart(chart)).map(chart => ({ chart, title: chartTitle(master, chart) }));
  const openQuick = (chartId: string, from: Screen) => { setSelectedChartId(chartId); setReturnScreen(from); setScreen("QUICK"); };
  const dataProps = { playerLabel: `${player.playerName ?? "PLAYER"} / ${player.iidxId ?? "ID未登録"}`, onResetScoreBp: async () => { await repository.resetScoreBp(player.playerId, new Date().toISOString()); await refresh(repository, player); return "SCORE/BPをリセットしました。前回値はQUICK INPUTで確認できます。"; }, onInitializeAll: async () => { await repository.initializeAllUserData(); setPlayer(undefined); setPlayerRecords(new Map()); setHistory([]); setSelectedChartId(undefined); setSelectedTrainingAttribute(undefined); setHomeThreshold("EASY_CLEAR"); setPlayerThreshold("EASY_CLEAR"); setScreen("HOME"); setSetup(await beginSetup(repository, id(), new Date().toISOString())); }, onOfficial: async (text: string) => { const current = await repository.listPlayerChartRecords(player.playerId); const preview = previewOfficialCsv(text, player.playerId, master.chartMaster.songs, master.chartMaster.charts, current, new Date().toISOString()); if (!confirm(previewMessage(preview.records.length, preview.errors))) return "キャンセルしました"; const result = await commitRecordImport(repository, player.playerId, preview.records, current, "official_csv", new Date().toISOString(), id); await refresh(repository, player); return `${result.records}件更新しました`; }, onTracker: async (text: string) => { const current = await repository.listPlayerChartRecords(player.playerId); const preview = previewClearTrackerCsv(text, player.playerId, master.chartMaster.charts, current, new Date().toISOString()); if (preview.errors.length) return preview.errors.join("\n"); if (!confirm(`${preview.changes.length}件を反映しますか？`)) return "キャンセルしました"; const result = await commitClearTrackerPreview(repository, preview, player.playerId, new Date().toISOString(), id); await refresh(repository, player); return `${result.records}件更新しました`; }, onTrackerExport: async () => { const current = await repository.listPlayerChartRecords(player.playerId); download("iidx-clear-tracker.csv", exportClearTrackerCsv(master.chartMaster.charts, master.chartMaster.songs, new Map(master.unofficial.records.map(record => [record.chartId, record.difficulty])), current), "text/csv;charset=utf-8"); }, onBackup: async () => { const now = new Date().toISOString(); download("iidx-clear-tracker-backup.json", JSON.stringify(await createBackup(repository, now), null, 2), "application/json"); await repository.saveAppMeta({ key: "lastBackupAt", value: now, updatedAt: now }); }, onRestore: async (text: string) => { const backup = parseBackup(text); validateBackupReferences(backup, new Set(master.chartMaster.charts.map(chart => chart.chartId))); if (!confirm("全ユーザーデータを置換しますか？")) return "キャンセルしました"; await restoreBackup(repository, backup, new Date().toISOString()); const players = await repository.listPlayers(); if (players[0]) { setPlayer(players[0]); await refresh(repository, players[0]); } return "復元しました"; } };
  const saveHomeThreshold = (value: ClearLamp) => { setHomeThreshold(value); void repository.saveUiSetting({ key: `homeThreshold:${player.playerId}`, value }); };
  const savePlayerThreshold = (value: ClearLamp) => { setPlayerThreshold(value); void repository.saveUiSetting({ key: `playerThreshold:${player.playerId}`, value }); };
  const page = screen === "HOME" ? <HomeScreen master={master} records={playerRecords} history={history} nextTraining={nextTraining.items} onReplaceNextTraining={nextTraining.replace} threshold={homeThreshold} onThreshold={saveHomeThreshold} onTraining={() => setScreen("TRAINING")} onSelect={chartId => openQuick(chartId, "HOME")} /> : screen === "TRAINING" ? <TrainingScreen master={master} records={playerRecords} result={training} selectedAttribute={selectedTrainingAttribute} onSelectedAttribute={setSelectedTrainingAttribute} onSelect={chartId => openQuick(chartId, "TRAINING")} /> : screen === "TRACKER" ? <TrackerScreen master={master} records={playerRecords} onSelect={chartId => openQuick(chartId, "TRACKER")} /> : screen === "HISTORY" ? <HistoryScreen master={master} history={history} /> : screen === "ANALYSIS" ? <AnalysisScreen master={master} records={playerRecords} training={training} onSelect={chartId => openQuick(chartId, "ANALYSIS")} /> : screen === "PLAYER" ? <PlayerScreen player={player} master={master} records={playerRecords} playThreshold={playerThreshold} onPlayThreshold={savePlayerThreshold} onUpdate={async patch => { const updated = await updatePlayerProfile(repository, player, patch, new Date().toISOString()); setPlayer(updated); }} onRadarUpdate={async values => { const updated = await updatePlayerRadar(repository, player, values, new Date().toISOString()); setPlayer(updated); }} onEreterUpdate={async value => { const updated = await updatePlayerEreterOverall(repository, player, value, new Date().toISOString()); setPlayer(updated); }} onRadarDetailsUpdate={async details => { const updated = await updatePlayerRadarDetails(repository, player, details, new Date().toISOString()); setPlayer(updated); }} /> : screen === "DATA" ? <DataScreen {...dataProps} /> : <QuickInput charts={choices} records={playerRecords} selectedChartId={selectedChartId} onCancel={() => setScreen(returnScreen)} onSave={async (chart, lamp: ClearLamp, score, bp) => { await updateQuickInput(repository, player.playerId, chart, lamp, score, bp, new Date().toISOString(), id); await refresh(repository, player); setScreen(returnScreen); }} />;
  return <main><header><h1>IIDX CLEAR TRACKER</h1><p>{player.playerName ?? "PLAYER"} / {dpRankLabel[player.highestDpRank]}</p></header><nav>{(["HOME", "TRAINING", "TRACKER", "QUICK", "HISTORY", "ANALYSIS", "PLAYER", "DATA"] as Screen[]).map(item => <button key={item} className={screen === item ? "active" : "secondary"} onClick={() => { setSelectedChartId(undefined); setScreen(item); }}>{item === "QUICK" ? "QUICK INPUT" : item}</button>)}</nav>{page}</main>;
}
